Iter9
ewik2k21/-URLShortening pull request #9
Opened 2023-11-18 13:15 UTC by ewik2k21

2023-11-21 18:57 UTC, vovean requested changes
1. Нет тестов
2. В файле может храниться всего 1 ссылка и она каждый раз переписывается? А если я хочу 2 линка сохранить?

2023-11-21 18:57 UTC, vovean commented on cmd/shortener/main.go
> +	mu    sync.Mutex `json:"-"`
нет смысла в таком json тэге, потому что приватные поля и так не используются в маршалинге

2023-11-22 17:33 UTC, ewik2k21 commented on cmd/shortener/main.go
> +	mu    sync.Mutex `json:"-"`
исправил

2023-11-28 21:42 UTC, vovean approved these changes

2023-11-29 09:43 UTC, merged